
jwt:
  header: Authorization
  secret: my-very-secret-key
spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
      - org.springframework.boot.autoconfigure.mongo.MongoReactiveAutoConfiguration
  server:
    error:
      whitelabel:
        enabled=false: